#!/usr/bin/env python3
"""
Run staged load tests against a local/staging API using seeded test tokens.

Usage:
    python scripts/seed_test_data.py --execute
    python scripts/load_test_suite.py --base-url http://127.0.0.1:8000

Requires:
    scripts/.seed/load_test_tokens.json (generated by seed script)

Production hosts are blocked unless --i-understand-production is passed.
"""

from __future__ import annotations

import argparse
import asyncio
import json
import os
import statistics
import sys
import time
from dataclasses import dataclass, field
from pathlib import Path
from urllib.parse import urlparse

import httpx

ROOT = Path(__file__).resolve().parent.parent
TOKEN_FILE = Path(__file__).resolve().parent / ".seed" / "load_test_tokens.json"
REPORT_FILE = Path(__file__).resolve().parent / ".seed" / "load_test_report.json"

PRODUCTION_HOST_MARKERS = (
    "happyexchange.net",
    "happiness-exchange.vercel.app",
    "hf.space",
)

SCENARIOS = [50, 100, 250, 500]

ENDPOINTS = [
    ("status", "GET", "/api/status/", False),
    ("items", "GET", "/api/items", False),
    ("community", "GET", "/api/community/impact", False),
    ("notifications", "GET", "/api/notifications", True),
    ("conversations", "GET", "/api/conversations/my", True),
]


@dataclass
class EndpointResult:
    name: str
    ok: int = 0
    failed: int = 0
    latencies_ms: list[float] = field(default_factory=list)

    def record(self, elapsed_ms: float, success: bool) -> None:
        self.latencies_ms.append(elapsed_ms)
        if success:
            self.ok += 1
        else:
            self.failed += 1

    @property
    def avg_ms(self) -> float:
        return statistics.mean(self.latencies_ms) if self.latencies_ms else 0.0

    @property
    def p95_ms(self) -> float:
        if not self.latencies_ms:
            return 0.0
        ordered = sorted(self.latencies_ms)
        idx = max(0, int(len(ordered) * 0.95) - 1)
        return ordered[idx]

    @property
    def max_ms(self) -> float:
        return max(self.latencies_ms) if self.latencies_ms else 0.0


def _is_production_url(base_url: str) -> bool:
    host = (urlparse(base_url).hostname or "").lower()
    return any(marker in host for marker in PRODUCTION_HOST_MARKERS)


def _load_tokens() -> list[str]:
    if not TOKEN_FILE.is_file():
        raise SystemExit(
            f"Missing {TOKEN_FILE}. Run: python scripts/seed_test_data.py --execute"
        )
    payload = json.loads(TOKEN_FILE.read_text(encoding="utf-8"))
    return [entry["token"] for entry in payload if entry.get("token")]


async def _hit(
    client: httpx.AsyncClient,
    method: str,
    path: str,
    *,
    headers: dict | None = None,
) -> tuple[bool, float, int]:
    started = time.perf_counter()
    try:
        response = await client.request(method, path, headers=headers, timeout=12.0)
        elapsed = (time.perf_counter() - started) * 1000
        return response.status_code < 500, elapsed, response.status_code
    except httpx.HTTPError:
        elapsed = (time.perf_counter() - started) * 1000
        return False, elapsed, 0


async def simulate_user(
    client: httpx.AsyncClient,
    user_idx: int,
    duration: int,
    token: str,
    results: dict[str, EndpointResult],
) -> None:
    headers = {"Authorization": f"Bearer {token}"}
    end_at = time.time() + duration

    while time.time() < end_at:
        for name, method, path, auth_required in ENDPOINTS:
            if time.time() >= end_at:
                break
            ok, elapsed, _ = await _hit(
                client,
                method,
                path,
                headers=headers if auth_required else None,
            )
            results[name].record(elapsed, ok)
        remaining = end_at - time.time()
        if remaining <= 0:
            break
        await asyncio.sleep(min(max(1.0, 15.0 / 4), remaining))


async def run_scenario(base_url: str, users: int, duration: int, tokens: list[str]) -> dict:
    results = {name: EndpointResult(name) for name, *_ in ENDPOINTS}
    started = time.perf_counter()

    async with httpx.AsyncClient(base_url=base_url.rstrip("/")) as client:
        tasks = [
            simulate_user(client, idx, duration, tokens[idx % len(tokens)], results)
            for idx in range(users)
        ]
        await asyncio.gather(*tasks)

    elapsed = round(time.perf_counter() - started, 2)
    total_ok = sum(result.ok for result in results.values())
    total_failed = sum(result.failed for result in results.values())
    total_requests = total_ok + total_failed

    endpoint_stats = []
    slowest = {"name": "", "p95_ms": 0.0}
    for result in results.values():
        if not result.latencies_ms:
            continue
        stat = {
            "name": result.name,
            "ok": result.ok,
            "failed": result.failed,
            "avg_ms": round(result.avg_ms, 2),
            "p95_ms": round(result.p95_ms, 2),
            "max_ms": round(result.max_ms, 2),
        }
        endpoint_stats.append(stat)
        if stat["p95_ms"] >= slowest["p95_ms"]:
            slowest = {"name": stat["name"], "p95_ms": stat["p95_ms"]}

    fail_rate = (total_failed / total_requests) if total_requests else 0.0
    avg_all = statistics.mean(
        [value for result in results.values() for value in result.latencies_ms]
    ) if total_requests else 0.0

    if fail_rate <= 0.01 and slowest["p95_ms"] <= 800:
        capacity = "comfortable at this level"
    elif fail_rate <= 0.05 and slowest["p95_ms"] <= 1500:
        capacity = "near capacity — monitor closely"
    else:
        capacity = "over capacity for current backend tier"

    return {
        "users": users,
        "duration_seconds": duration,
        "elapsed_seconds": elapsed,
        "total_requests": total_requests,
        "failed_requests": total_failed,
        "failure_rate_pct": round(fail_rate * 100, 2),
        "average_response_ms": round(avg_all, 2),
        "slowest_endpoint": slowest,
        "endpoints": endpoint_stats,
        "estimated_capacity": capacity,
    }


def _print_scenario(summary: dict) -> None:
    print(f"\n=== {summary['users']} concurrent users ===", flush=True)
    print(f"Total requests: {summary['total_requests']}", flush=True)
    print(f"Failed requests: {summary['failed_requests']} ({summary['failure_rate_pct']}%)", flush=True)
    print(f"Average response time: {summary['average_response_ms']} ms", flush=True)
    print(
        "Slowest endpoint: "
        f"{summary['slowest_endpoint']['name']} "
        f"(p95 {summary['slowest_endpoint']['p95_ms']} ms)",
        flush=True,
    )
    print(f"Estimated capacity: {summary['estimated_capacity']}", flush=True)
    for endpoint in summary["endpoints"]:
        print(
            f"  {endpoint['name']}: avg={endpoint['avg_ms']}ms "
            f"p95={endpoint['p95_ms']}ms failed={endpoint['failed']}",
            flush=True,
        )


async def run_suite(base_url: str, duration: int, scenarios: list[int]) -> dict:
    tokens = _load_tokens()
    summaries = []
    for users in scenarios:
        if users > len(tokens) and users > 1:
            print(f"Note: cycling {len(tokens)} seeded tokens across {users} virtual users.")
        print(f"\nStarting scenario: {users} concurrent users ({duration}s)…", flush=True)
        summary = await run_scenario(base_url, users, duration, tokens)
        summaries.append(summary)
        _print_scenario(summary)
    report = {"base_url": base_url, "duration_per_scenario": duration, "scenarios": summaries}
    REPORT_FILE.parent.mkdir(parents=True, exist_ok=True)
    REPORT_FILE.write_text(json.dumps(report, indent=2), encoding="utf-8")
    print(f"\nFull report written to: {REPORT_FILE}")
    return report


def main() -> int:
    parser = argparse.ArgumentParser(description="Run seeded load-test scenarios.")
    parser.add_argument("--base-url", default=os.environ.get("LOAD_TEST_BASE_URL", "http://127.0.0.1:8000"))
    parser.add_argument("--duration", type=int, default=20, help="Seconds per scenario")
    parser.add_argument(
        "--scenarios",
        default="50,100,250,500",
        help="Comma-separated concurrent user counts",
    )
    parser.add_argument(
        "--i-understand-production",
        action="store_true",
        help="Required to run against production/staging public hosts",
    )
    args = parser.parse_args()

    if _is_production_url(args.base_url) and not args.i_understand_production:
        print("Refusing production host. Use localhost or pass --i-understand-production.", file=sys.stderr)
        return 2

    scenarios = [int(value.strip()) for value in args.scenarios.split(",") if value.strip()]
    for users in scenarios:
        if users > 500:
            print("Refusing >500 users in one suite.", file=sys.stderr)
            return 2

    asyncio.run(run_suite(args.base_url, args.duration, scenarios))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
